---
title: "final_proj"
author: "Sabrina Chok"
date: "4/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(base)

download.file(url = "https://raw.githubusercontent.com/fivethirtyeight/uber-tlc-foil-response/master/uber-trip-data/uber-raw-data-apr14.csv", destfile = "apr_14.csv", mode = "wb")

apr14 <- read.csv("apr_14.csv")

download.file(url = "https://raw.githubusercontent.com/fivethirtyeight/uber-tlc-foil-response/master/Uber-Jan-Feb-FOIL.csv", destfile = "jan_feb15.csv", mode = "wb")

jan_feb15 <- read.csv("jan_feb15.csv")

fs::file_delete(c("apr_14.csv", "jan_feb15.csv"))
```

```{r}
jan_feb15  %>%  
  mutate(base_name = case_when(dispatching_base_number == "B02512" ~ "Unter",
                               dispatching_base_number == "B02598" ~	"Hinter",
                               dispatching_base_number == "B02617" ~ "Weiter",
                               dispatching_base_number == "B02682" ~	"Schmecken",
                               dispatching_base_number == "B02764" ~	"Danach-NY",
                               dispatching_base_number == "B02765" ~	"Grun",
                               dispatching_base_number == "B02835" ~	"Dreist",
                               dispatching_base_number == "B02836" ~	"Drinnen")) %>%
  mutate(date = toString(date), 
         date = as.Date(jan_feb15$date, "%m/%d/%Y")) %>% 
  mutate(day = wday(date, label = TRUE),
         month = month(date)) %>% 
  group_by(day) %>% 
  summarize(trip_t = sum(trips),
            vehicle_t = sum(active_vehicles),
            avgtrip_day = mean(trips)) %>% 
  ungroup %>% 
  ggplot(aes(x =))

  
  
  
```








